In [2]:
import uproot
ttbar = uproot.open("/eos/uscms/store/user/srosenzw/sixb/ntuples/Summer2018UL/maxbtag_4b/TTJets/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/ntuple.root")
ttbar = ttbar['sixBtree']
ttbar.keys()

['Run',
 'LumiSec',
 'Event',
 'n_other_pv',
 'rhofastjet_all',
 'PFHT',
 'HEMWeight',
 'PUIDWeight',
 'PUIDWeight_up',
 'PUIDWeight_down',
 'triggerScaleFactor',
 'triggerDataEfficiency',
 'triggerMcEfficiency',
 'triggerScaleFactorUp',
 'triggerDataEfficiencyUp',
 'triggerMcEfficiencyUp',
 'triggerScaleFactorDown',
 'triggerDataEfficiencyDown',
 'triggerMcEfficiencyDown',
 'X_m',
 'X_pt',
 'X_eta',
 'X_phi',
 'Y_m',
 'Y_pt',
 'Y_eta',
 'Y_phi',
 'HX_m',
 'HX_pt',
 'HX_eta',
 'HX_phi',
 'H1_m',
 'H1_pt',
 'H1_eta',
 'H1_phi',
 'H2_m',
 'H2_pt',
 'H2_eta',
 'H2_phi',
 'HX_b1_m',
 'HX_b1_pt',
 'HX_b1_eta',
 'HX_b1_phi',
 'HX_b1_btag',
 'HX_b2_m',
 'HX_b2_pt',
 'HX_b2_eta',
 'HX_b2_phi',
 'HX_b2_btag',
 'H1_b1_m',
 'H1_b1_pt',
 'H1_b1_eta',
 'H1_b1_phi',
 'H1_b1_btag',
 'H1_b2_m',
 'H1_b2_pt',
 'H1_b2_eta',
 'H1_b2_phi',
 'H1_b2_btag',
 'H2_b1_m',
 'H2_b1_pt',
 'H2_b1_eta',
 'H2_b1_phi',
 'H2_b1_btag',
 'H2_b2_m',
 'H2_b2_pt',
 'H2_b2_eta',
 'H2_b2_phi',
 'H2_b2_btag',
 'n_muon',
 'n_ele

In [16]:
tree = SixB("/eos/uscms/store/user/srosenzw/sixb/ntuples/Summer2018UL/maxbtag_4b/Official_NMSSM/NMSSM_XToYHTo6B_MX-950_MY-800_TuneCP5_13TeV-madgraph-pythia8/ntuple.root", feyn=False)
tree.scale

[21:16:16] Loading                                                  ]8;id=130258;file:///uscms/home/srosenzw/nobackup/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py\signal.py]8;;\:]8;id=326811;file:///uscms/home/srosenzw/nobackup/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py#92\92]8;;\
           Summer2018UL/maxbtag_4b/Official_NMSSM/NMSSM_XToYHTo6B_M             
           X-950_MY-800_TuneCP5_13TeV-madgraph-pythia8/ntuple.root.             
           ..                                                                   


0.08961

In [6]:
import uproot
f = uproot.open("output.root")
t = f['sixBtree']
t['genWeight'].array()
t['PUIDWeight_down'].array(), t['PUIDWeight'].array(), t['PUIDWeight_up'].array()

['h_cutflow;1', 'h_cutflow_unweighted;1', 'n_ele;1', 'n_mu;1', 'n_presel_jet;1', 'sixBtree;1']


(<Array [0.806, 0.777, 0.662, ..., 0.771, 0.691, 1.33] type='116 * float64'>,
 <Array [0.857, 0.82, 0.75, 0.939, ..., 0.815, 0.79, 1.18] type='116 * float64'>,
 <Array [0.91, 0.865, 0.847, ..., 0.861, 0.899, 1.03] type='116 * float64'>)

In [7]:
# t['genWeight'].array()[0]*59740*1.0 * (5.824E-01)**3
genWeight = t['genWeight'].array()
np.sum(genWeight < 0) / len(genWeight), genWeight

(0.3333333333333333,
 <Array [5.52e+03, 5.52e+03, -5.52e+03] type='3 * float32'>)

In [1]:
import uproot
f = uproot.open("data/puid/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root")

In [2]:
[key for key in f.keys() if '2018' in key]

['h2_eff_mcUL2018_L;1',
 'h2_eff_mcUL2018_M;1',
 'h2_eff_mcUL2018_T;1',
 'h2_eff_sfUL2018_L;1',
 'h2_eff_sfUL2018_M;1',
 'h2_eff_sfUL2018_T;1',
 'h2_eff_sfUL2018_L_Systuncty;1',
 'h2_eff_sfUL2018_M_Systuncty;1',
 'h2_eff_sfUL2018_T_Systuncty;1']

In [4]:
f['h2_eff_sfUL2018_T']

<TH2F (version 4) at 0x7f08bae8f580>

In [7]:
f['h2_eff_mcUL2018_T'].to_numpy(), f['h2_eff_sfUL2018_T'].to_numpy(), f['h2_eff_sfUL2018_T_Systuncty'].to_numpy()

((array([[0.7864, 0.7586, 0.7022, 0.653 , 0.7043, 0.7893, 0.78  , 0.7025,
          0.6351, 0.7541, 0.7509, 0.7863],
         [0.8731, 0.8022, 0.7945, 0.7411, 0.792 , 0.8613, 0.8539, 0.7952,
          0.7408, 0.7967, 0.8169, 0.8788],
         [0.8471, 0.772 , 0.7777, 0.6385, 0.7123, 0.8227, 0.8155, 0.7198,
          0.6233, 0.7919, 0.7706, 0.8432],
         [0.8455, 0.7558, 0.7665, 0.5697, 0.6713, 0.8   , 0.7929, 0.6623,
          0.5605, 0.7717, 0.7727, 0.8425]], dtype=float32),
  array([20., 25., 30., 40., 50.]),
  array([-5.   , -3.   , -2.75 , -2.5  , -2.   , -1.479,  0.   ,  1.479,
          2.   ,  2.5  ,  2.75 ,  3.   ,  5.   ])),
 (array([[0.9123855 , 0.9777221 , 1.005554  , 0.89203674, 0.93766856,
          0.9437476 , 0.94923085, 0.92740214, 0.90410954, 0.89696324,
          0.9484619 , 0.9306881 ],
         [0.9325392 , 0.97693837, 0.98653245, 0.93766016, 0.9598485 ,
          0.96679443, 0.9700199 , 0.9488179 , 0.9214363 , 0.95832807,
          0.9412412 , 0.92705965],
    